In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [6]:
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [20]:
monthly_sales = df_plotly.groupby(["month","product"], as_index=False)[['customers','units','sales']].sum()
monthly_sales

        month product  customers  units  sales
0  2024-01-01       A        135    119    481
1  2024-01-01       B        153     84    326
2  2024-02-01       A        176    151    405
3  2024-02-01       B        171    138    405
4  2024-03-01       A        184     69    504
5  2024-03-01       B        196     82    327
6  2024-04-01       A        181    129    496
7  2024-04-01       B        163     73    359
8  2024-05-01       A        163     76    421
9  2024-05-01       B        118    131    513
10 2024-06-01       A        141    124    392
11 2024-06-01       B        111    138    404

In [21]:
fig = px.line(
    data_frame = monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot: Monthly Total Sales",
    color='product'
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [16]:
regional_sales = df_plotly.groupby("region", as_index=False)[['customers','units','sales']].sum()
regional_sales

  region  customers  units  sales
0   East        614    501   1559
1  North        605    450   1800
2  South        673    363   1674

In [18]:
fig = px.bar(
    data_frame = regional_sales,
    x="region",
    y="sales",
    title="Regional Total Sales"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

fig.show()

In [22]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Scatter Plot: Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()