In [3]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/regression/test.csv')
df.head()

   Hours Studied  Grade on Exam
0              2             69
1              9             98
2              5             82
3              5             77
4              3             71

In [7]:
x = df['Hours Studied']
y = df['Grade on Exam']

x_mean = x.mean()
y_mean = y.mean()

In [8]:
x_mean

np.float64(4.8)

In [9]:
y_mean

np.float64(77.8)

In [11]:
beta1 = ((x - x_mean) * (y - y_mean)).sum() / ((x - x_mean) ** 2).sum()
beta0 = y_mean - beta1 * x_mean

print(f"Mean of X: {x_mean:.2f}")
print(f"Mean of Y: {y_mean:.2f}")
print(f"Intercept (β0): {beta0:.4f}")
print(f"Slope (β1): {beta1:.4f}")
print(f"Fitted line: y_hat = {beta0:.2f} + {beta1:.2f}x")

Mean of X: 4.80
Mean of Y: 77.80
Intercept (β0): 55.0355
Slope (β1): 4.7426
Fitted line: y_hat = 55.04 + 4.74x

$$Y..= \beta_0 + \beta_1 X$$

In [17]:
X = 0

Y_hat = beta0 + beta1*X
print(f'{X} hours of work results {Y_hat}')

0 hours of work results 55.03550295857988

In [ ]:
beta1 = 1.5

In [13]:
df.sort_values(by='Hours Studied')

   Hours Studied  Grade on Exam
6              1             55
0              2             69
9              2             64
4              3             71
2              5             82
3              5             77
8              6             84
5              7             84
7              8             94
1              9             98

In [1]:
import pandas as pd
import numpy  as np
from sklearn.linear_model import LinearRegression

ads = pd.read_csv('../data/regression/advertising_and_sales.csv')
ads.head()

        tv     radio  social_media influencer      sales
0  16000.0   6566.23       2907.98       Mega   54732.76
1  13000.0   9237.76       2409.57       Mega   46677.90
2  41000.0  15886.45       2913.41       Mega  150177.83
3  83000.0  30020.03       6922.30       Mega  298246.34
4  15000.0   8437.41       1406.00      Micro   56594.18

In [2]:
from sklearn.linear_model import LinearRegression


channels  = ['tv','radio','social_media']


# import statsmodels.api as sm

# X = sm.add_constant(X)   # IMPORTANT: add intercept
# model = sm.OLS(y, X).fit()

# model.rsquared
from utils import rsquered

for channel in channels:

    X = ads[[channel]]
    y = ads['sales']
    
    model = LinearRegression()
    model.fit(X,y)
    
    y_hat = model.predict(X)

    r2 = 1 - rsquered(y,y_hat)
    rmse = np.sqrt(np.mean((y-y_hat)**2))



    print(f'Intercept {channel}: {model.intercept_:2f}')
    print(f'Coef {channel}: {model.coef_[0]:f}')
    print(f'R_Squared {channel}: {r2}')
    print(f'RMSE {channel}: {rmse}')
    print(100*'-')

Intercept tv: -132.492506
Coef tv: 3.561514
R_Squared tv: 0.9989949845239908
RMSE tv: 2948.5897129351397
----------------------------------------------------------------------------------------------------
Intercept radio: 40586.800679
Coef radio: 8.361628
R_Squared radio: 0.7545316512195284
RMSE radio: 46081.40604818036
----------------------------------------------------------------------------------------------------
Intercept social_media: 118672.571739
Coef social_media: 22.187863
R_Squared social_media: 0.278199728097955
RMSE social_media: 79019.9029555142
----------------------------------------------------------------------------------------------------

$$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2$$

In [9]:
corr = ads[['tv','radio','social_media','sales']].corr()
corr

                    tv     radio  social_media     sales
tv            1.000000  0.869158      0.527687  0.999497
radio         0.869158  1.000000      0.606338  0.868638
social_media  0.527687  0.606338      1.000000  0.527446
sales         0.999497  0.868638      0.527446  1.000000

In [7]:
import plotly.express as px

fig = px.imshow(corr)
fig.show()

## Multiple Linear Regression

In [11]:
X = ads[['tv','radio','social_media']]
y = ads['sales']

In [15]:
model = LinearRegression()
model.fit(X,y)

y_hat = model.predict(X)

In [ ]:
1 - rsquered(y,y_hat)

np.float64(0.9989950218000194)

In [20]:
from utils import rmse
rmse(y,y_hat)

np.float64(2948.5350308251286)

In [16]:
model.coef_

array([ 3.56256963, -0.00397038,  0.00496396])

In [37]:
['male', 'famale']

['male', 'famale']

In [ ]:
CASE WHEN MEGA THEN 1 ELSE 0
CASE WEHEN MPLSAPD THEN 1EL S

In [21]:
ads.head()

        tv     radio  social_media influencer      sales
0  16000.0   6566.23       2907.98       Mega   54732.76
1  13000.0   9237.76       2409.57       Mega   46677.90
2  41000.0  15886.45       2913.41       Mega  150177.83
3  83000.0  30020.03       6922.30       Mega  298246.34
4  15000.0   8437.41       1406.00      Micro   56594.18

In [32]:
ads["influencer"] = pd.Categorical(
    ads["influencer"],
    categories=["Mega", "Macro", "Micro", "Nano"]
)

In [40]:
X = pd.get_dummies(ads['influencer'],
               drop_first=True,
               dtype= int
               )

      Mega  Macro  Micro  Nano
0        1      0      0     0
1        1      0      0     0
2        1      0      0     0
3        1      0      0     0
4        0      0      1     0
...    ...    ...    ...   ...
4541     0      0      1     0
4542     0      0      0     1
4543     0      0      1     0
4544     0      1      0     0
4545     0      0      1     0

[4546 rows x 4 columns]

In [35]:
model = LinearRegression()

model.fit(X,y)
model.coef_

array([5653.24247589, 1165.46236178, 1295.91918954])

$$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3$$